server:
  port: 9993

spring:
  application:
    name: API-VIDEOS
  cloud:
    nacos:
      server-addr: 8.136.187.29:8848

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yingxue?characterEncoding=UTF-8&useSSL=false
    username: root
    password: zxh228..
  redis:
    host: 127.0.0.1
    port: 6379
  rabbitmq:
    host: 8.136.187.29
    port: 5672
    username: guest
    password: guest
    virtual-host: / #类似于数据库概念


mybatis:
  mapper-locations: classpath:com/zhangxuhui/mapper/*.xml
  type-aliases-package: com.zhangxuhui.entity

logging:
  level:
    com:
      baizhi:
        dao: debug
