server:
  port: 9095
spring:
  application:
    name: API-SEARCH
  cloud:
    nacos:
      server-addr: 8.136.187.29:8848

  rabbitmq:
    host: 8.136,187,29
    port: 5672
    username: guest
    password: guest
    virtual-host: /
